version: "3"

services:
  web:
    build: .
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - JWT=${JWT}
      - DATABASE_URL=${DATABASE_URL}  # The Render DB URL will be passed here
    env_file:
      - .env  # Loads the environment variables from .env file
